package view.form;

import controller.FilmeController;
import javax.swing.JButton;
import javax.swing.JLabel;
import javax.swing.JTextField;

/**
 * Created by marcus.rodrigues on 18/06/2015.
 */
public class FilmePainelFormulario extends javax.swing.JPanel{

    private FilmeController controller;
    private JButton salvarButton;
    private JButton voltarButton;
    private JTextField codTextField;
    private JTextField tituloTextField;
    private JTextField generoTextField;
    private JTextField sinopseTextField;
    private JTextField dataInicioTextField;
    private JTextField dataFinalTextField;
    private JLabel codLabel;
    private JLabel tituloLabel;
    private JLabel generoLabel;
    private JLabel sinopseLabel;
    private JLabel dataInicioLabel;
    private JLabel dataFinalLabel;
    private JLabel labelPainelFormulario;

    /**
     * Creates new form PainelFormulario
     */
    public FilmePainelFormulario() {
        initComponents();
    }

    public FilmePainelFormulario(FilmeController controller) {
        this.controller=controller;
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        salvarButton = new javax.swing.JButton();
        voltarButton = new javax.swing.JButton();
        codTextField = new javax.swing.JTextField();
        tituloTextField = new javax.swing.JTextField();
        generoTextField = new javax.swing.JTextField();
        sinopseTextField = new javax.swing.JTextField();
        dataInicioTextField = new javax.swing.JTextField();
        dataFinalTextField = new javax.swing.JTextField();
        codLabel = new javax.swing.JLabel();
        tituloLabel = new javax.swing.JLabel();
        generoLabel = new javax.swing.JLabel();
        sinopseLabel = new javax.swing.JLabel();
        dataInicioLabel = new javax.swing.JLabel();
        dataFinalLabel = new javax.swing.JLabel();
        labelPainelFormulario = new javax.swing.JLabel();

        salvarButton.setText("Cadastrar");
        salvarButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoSalvarActionPerformed(evt);
            }
        });

        voltarButton.setText("Voltar");
        voltarButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoVoltarActionPerformed(evt);
            }
        });

        codLabel.setText("Cod:");
        tituloLabel.setText("Titulo:");
        generoLabel.setText("Genero:");
        sinopseLabel.setText("Sinopse:");
        dataInicioLabel.setText("Data Inicio:");
        dataFinalLabel.setText("Data Final:");

        labelPainelFormulario.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        labelPainelFormulario.setText("Cadastro de Pacientes");
    }

        private void botaoSalvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoSalvarActionPerformed
            controller.salvarFilme(
                    this.codTextField.getText(),
                    this.tituloTextField.getText(),
                    this.generoTextField.getText(),
                    this.sinopseTextField.getText(),
                    this.dataInicioTextField.getText(),
                    this.dataFinalTextField.getText());
        }//GEN-LAST:event_botaoSalvarActionPerformed

        private void botaoVoltarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoVoltarActionPerformed
            controller.voltarPrincipal();
        }//GEN-LAST:event_botaoVoltarActionPerformed

        public JButton getBotaoSalvar() {
            return salvarButton;
        }

        public JButton getBotaoVoltar() {
            return voltarButton;
        }

        public JLabel getLabelPainelFormulario() {
            return labelPainelFormulario;
        }

        public JTextField getTextCodFilme() {
            return codTextField;
        }

        public JTextField getTextTitulo() {
            return tituloTextField;
        }

        public JTextField getTextGenero() {
            return generoTextField;
        }

        public JTextField getTextSinopse() {
            return sinopseTextField;
        }
        public JTextField getTextDataInicio() {
            return dataInicioTextField;
        }
        public JTextField getTextDataFinal() {
            return dataFinalTextField;
        }

        public void zerarCampos(){
                    this.codTextField.setText("");
                    this.tituloTextField.setText("");
                    this.generoTextField.setText("");
                    this.sinopseTextField.setText("");
                    this.dataInicioTextField.setText("");
                    this.dataFinalTextField.setText("");
        }
        public void carregaDados(String codFilme, String titulo, String genero, String sinopse, String dataInicio, String dataFinal) {
            this.codTextField.setText(codFilme);
            this.tituloTextField.setText(titulo);
            this.generoTextField.setText(genero);
            this.sinopseTextField.setText(sinopse);
            this.dataInicioTextField.setText(dataInicio);
            this.dataFinalTextField.setText(dataFinal);
        }
        public void habilitaEdicaoFormFilme(boolean valor) {
            this.codTextField.setEditable(valor);
            this.tituloTextField.setEditable(valor);
            this.generoTextField.setEditable(valor);
            this.sinopseTextField.setEditable(valor);
            this.dataInicioTextField.setEditable(valor);
            this.dataFinalTextField.setEditable(valor);
        }
    }
